export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ORDERS_INVOICE_REQUEST = "ORDERS_INVOICE_REQUEST";
export const ORDERS_INVOICE_SUCCESS = "ORDERS_INVOICE_SUCCESS";
export const ORDERS_INVOICE_FAIL = "ORDERS_INVOICE_FAIL";
export const ORDERS_INVOICE_RESET = "ORDERS_INVOICE_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";