export const CONSUMER_LOGIN_REQUEST = "CONSUMER_LOGIN_REQUEST";
export const CONSUMER_LOGIN_SUCCESS = "CONSUMER_LOGIN_SUCCESS";
export const CONSUMER_LOGIN_FAIL = "CONSUMER_LOGIN_FAIL";

export const  REGISTER_CONSUMER_REQUEST = "REGISTER_   CONSUMER_REQUEST";
export const  REGISTER_CONSUMER_SUCCESS = "REGISTER_   CONSUMER_SUCCESS";
export const  REGISTER_CONSUMER_FAIL = "REGISTER_  CONSUMER_FAIL";

export const RESELLER_LOGIN_REQUEST = "RESELLER_LOGIN_REQUEST";
export const RESELLER_LOGIN_SUCCESS = "RESELLER_LOGIN_SUCCESS";
export const RESELLER_LOGIN_FAIL = "RESELLER_LOGIN_FAIL";

export const REGISTER_RESELLER_REQUEST = "REGISTER_RESELLER_REQUEST";
export const REGISTER_RESELLER_SUCCESS = "REGISTER_RESELLER_SUCCESS";
export const REGISTER_RESELLER_FAIL = "REGISTER_RESELLER_FAIL";

export const LOAD_RESELLER_REQUEST = "LOAD_RESELLER_REQUEST"; 
export const LOAD_RESELLER_SUCCESS = "LOAD_RESELLER_SUCCESS"; 
export const LOAD_RESELLER_FAIL = "LOAD_RESELLER_FAIL";

export const LOAD_CONSUMER_REQUEST = "LOAD_CONSUMER_REQUEST"; 
export const LOAD_CONSUMER_SUCCESS = "LOAD_CONSUMER_SUCCESS"; 
export const LOAD_CONSUMER_FAIL = "LOAD_CONSUMER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FALI";

export const CLEAR_ERRORS = "CLEAR_ERRORS";