export const CONSUMER_LOGIN_REQUEST = "CONSUMER_LOGIN_REQUEST";
export const CONSUMER_LOGIN_SUCCESS = "CONSUMER_LOGIN_SUCCESS";
export const CONSUMER_LOGIN_FAIL = "CONSUMER_LOGIN_FAIL";

export const  REGISTER_CONSUMER_REQUEST = "REGISTER_   CONSUMER_REQUEST";
export const  REGISTER_CONSUMER_SUCCESS = "REGISTER_   CONSUMER_SUCCESS";
export const  REGISTER_CONSUMER_FAIL = "REGISTER_  CONSUMER_FAIL";

export const RESELLER_LOGIN_REQUEST = "RESELLER_LOGIN_REQUEST";
export const RESELLER_LOGIN_SUCCESS = "RESELLER_LOGIN_SUCCESS";
export const RESELLER_LOGIN_FAIL = "RESELLER_LOGIN_FAIL";

export const REGISTER_RESELLER_REQUEST = "REGISTER_RESELLER_REQUEST";
export const REGISTER_RESELLER_SUCCESS = "REGISTER_RESELLER_SUCCESS";
export const REGISTER_RESELLER_FAIL = "REGISTER_RESELLER_FAIL";

export const LOAD_RESELLER_REQUEST = "LOAD_RESELLER_REQUEST"; 
export const LOAD_RESELLER_SUCCESS = "LOAD_RESELLER_SUCCESS"; 
export const LOAD_RESELLER_FAIL = "LOAD_RESELLER_FAIL";

export const LOAD_CONSUMER_REQUEST = "LOAD_CONSUMER_REQUEST"; 
export const LOAD_CONSUMER_SUCCESS = "LOAD_CONSUMER_SUCCESS"; 
export const LOAD_CONSUMER_FAIL = "LOAD_CONSUMER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FALI";

export const UPDATE_RESELLER_PROFILE_REQUEST = "UPDATE_RESELLER_PROFILE_REQUEST";
export const UPDATE_RESELLER_PROFILE_SUCCESS = "UPDATE_RESELLER_PROFILE_SUCCESS";
export const UPDATE_RESELLER_PROFILE_RESET = "UPDATE_RESELLER_PROFILE_RESET";
export const UPDATE_RESELLER_PROFILE_FAIL = "UPDATE_RESELLER_PROFILE_FAIL";

export const UPDATE_CONSUMER_PROFILE_REQUEST = "UPDATE_CONSUMER_PROFILE_REQUEST";
export const UPDATE_CONSUMER_PROFILE_SUCCESS = "UPDATE_CONSUMER_PROFILE_SUCCESS";
export const UPDATE_CONSUMER_PROFILE_RESET = "UPDATE_CONSUMER_PROFILE_RESET";
export const UPDATE_CONSUMER_PROFILE_FAIL = "UPDATE_CONSUMER_PROFILE_FAIL";

export const SUBMIT_MESSAGE_REQUEST = "SUBMIT_MESSAGE_REQUEST";
export const SUBMIT_MESSAGE_SUCCESS = "SUBMIT_MESSAGE_SUCCESS";
export const SUBMIT_MESSAGE_FAIL = "SUBMIT_MESSAGE_FAIL";

export const UPDATE_CONSUMER_PASSWORD_REQUEST = "UPDATE_CONSUMER_PASSWORD_REQUEST";
export const UPDATE_CONSUMER_PASSWORD_SUCCESS = "UPDATE_CONSUMER_PASSWORD_SUCCESS";
export const UPDATE_CONSUMER_PASSWORD_RESET = "UPDATE_CONSUMER_PASSWORD_RESET";
export const UPDATE_CONSUMER_PASSWORD_FAIL = "UPDATE_CONSUMER_PASSWORD_FAIL";

export const UPDATE_RESEllER_PASSWORD_REQUEST = "UPDATE_RESEllER_PASSWORD_REQUEST";
export const UPDATE_RESEllER_PASSWORD_SUCCESS = "UPDATE_RESEllER_PASSWORD_SUCCESS";
export const UPDATE_RESEllER_PASSWORD_RESET = "UPDATE_RESEllER_PASSWORD_RESET";
export const UPDATE_RESEllER_PASSWORD_FAIL = "UPDATE_RESEllER_PASSWORD_FAIL";

export const SUBSCRIBE_REQUEST = "SUBSCRIBE_REQUEST";
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS";
export const SUBSCRIBE_FAIL = "SUBSCRIBE_FAIL";

export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST';
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS';
export const APPLY_COUPON_FAIL = 'APPLY_COUPON_FAIL';

export const GET_TESTIMONIAL_REQUEST = "GET_TESTIMONIAL_REQUEST";
export const GET_TESTIMONIAL_SUCCESS = "GET_TESTIMONIAL_SUCCESS";
export const GET_TESTIMONIAL_FAIL = "GET_TESTIMONIAL_FAIL";

export const  ORDER_CANCEL_REQUEST = "ORDER_CANCEL_REQUEST";
export const  ORDER_CANCEL_SUCCESS = "ORDER_CANCEL_SUCCESS";
export const  ORDER_CANCEL_FAIL = "ORDER_CANCEL_FAIL";
export const  ORDER_CANCEL_RESET = "ORDER_CANCEL_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";